apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp3-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp3
  template:
    metadata: # Dictionary
      name: myapp-Deploment
      labels: # Dictionary
        app: myapp3
    spec:
      containers: # List
        - name: myapp3
          image: stacksimplify/kubenginx:3.0.0
          ports:
            - containerPort: 80